checks:
    go: true
build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            environment:
                go:
                    version: go1.9.2
            tests:
                override:
                    - go-scrutinizer-run
                    - govet-run
                    - golint-run
        tests:
            environment:
                go:
                    version: go1.9.2
        coverage:
            tests:
                override:
                    -
                        command: go test -coverprofile=cover.out
                        coverage:
                            file: 'cover.out'
                            format: 'go-cc'
